wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1661206505.600135
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.13.2
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: adam
